# Generated by Django 2.2 on 2020-10-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=100)),
                ('movie1', models.CharField(max_length=100)),
                ('movie2', models.CharField(max_length=100)),
                ('movie3', models.CharField(max_length=100)),
                ('elem1', models.CharField(max_length=100)),
                ('elem2', models.CharField(max_length=100)),
                ('elem3', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('country1', models.CharField(max_length=100)),
                ('country2', models.CharField(max_length=100)),
                ('country3', models.CharField(max_length=100)),
                ('actor1', models.CharField(max_length=100)),
                ('actor2', models.CharField(max_length=100)),
                ('actor3', models.CharField(max_length=100)),
                ('director1', models.CharField(max_length=100)),
                ('director2', models.CharField(max_length=100)),
                ('director3', models.CharField(max_length=100)),
                ('oscar', models.BooleanField()),
                ('years1', models.CharField(max_length=100)),
                ('years2', models.CharField(max_length=100)),
                ('years3', models.CharField(max_length=100)),
                ('food1', models.CharField(max_length=100)),
                ('food2', models.CharField(max_length=100)),
                ('food3', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Sexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='none/no-img.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=100)),
            ],
        ),
    ]
