# Generated by Django 2.2 on 2020-10-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actors',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='Directors',
        ),
        migrations.DeleteModel(
            name='Elements',
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.DeleteModel(
            name='Places',
        ),
        migrations.DeleteModel(
            name='Sexes',
        ),
        migrations.DeleteModel(
            name='Years',
        ),
    ]
