# Generated by Django 2.2 on 2020-11-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProfile',
        ),
    ]
