# Generated by Django 2.2 on 2020-10-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='none/no-img.jpg', upload_to='')),
            ],
        ),
    ]
