# Generated by Django 2.2 on 2020-10-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_nowy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nowy',
        ),
    ]
