# Generated by Django 2.2 on 2020-10-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20201020_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nowy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyk', models.CharField(max_length=400)),
                ('ziomek', models.CharField(max_length=400)),
                ('pole', models.CharField(max_length=400)),
            ],
        ),
    ]
