# Generated by Django 2.2 on 2020-10-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_nowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowy',
            name='traktor',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
